// @generated by protoc-gen-connect-es v1.0.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/aspect_plugin.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BEPEventCallbackReq, BEPEventCallbackRes, CustomCommandsReq, CustomCommandsRes, ExecuteCustomCommandReq, ExecuteCustomCommandRes, PostBuildHookReq, PostBuildHookRes, PostRunHookReq, PostRunHookRes, PostTestHookReq, PostTestHookRes, PromptRunReq, PromptRunRes, SetupReq, SetupRes } from "./aspect_plugin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.Plugin
 */
export declare const Plugin: {
  readonly typeName: "proto.Plugin",
  readonly methods: {
    /**
     * @generated from rpc proto.Plugin.BEPEventCallback
     */
    readonly bEPEventCallback: {
      readonly name: "BEPEventCallback",
      readonly I: typeof BEPEventCallbackReq,
      readonly O: typeof BEPEventCallbackRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.Plugin.CustomCommands
     */
    readonly customCommands: {
      readonly name: "CustomCommands",
      readonly I: typeof CustomCommandsReq,
      readonly O: typeof CustomCommandsRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.Plugin.ExecuteCustomCommand
     */
    readonly executeCustomCommand: {
      readonly name: "ExecuteCustomCommand",
      readonly I: typeof ExecuteCustomCommandReq,
      readonly O: typeof ExecuteCustomCommandRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.Plugin.PostBuildHook
     */
    readonly postBuildHook: {
      readonly name: "PostBuildHook",
      readonly I: typeof PostBuildHookReq,
      readonly O: typeof PostBuildHookRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.Plugin.PostTestHook
     */
    readonly postTestHook: {
      readonly name: "PostTestHook",
      readonly I: typeof PostTestHookReq,
      readonly O: typeof PostTestHookRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.Plugin.PostRunHook
     */
    readonly postRunHook: {
      readonly name: "PostRunHook",
      readonly I: typeof PostRunHookReq,
      readonly O: typeof PostRunHookRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.Plugin.Setup
     */
    readonly setup: {
      readonly name: "Setup",
      readonly I: typeof SetupReq,
      readonly O: typeof SetupRes,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service proto.Prompter
 */
export declare const Prompter: {
  readonly typeName: "proto.Prompter",
  readonly methods: {
    /**
     * @generated from rpc proto.Prompter.Run
     */
    readonly run: {
      readonly name: "Run",
      readonly I: typeof PromptRunReq,
      readonly O: typeof PromptRunRes,
      readonly kind: MethodKind.Unary,
    },
  }
};

