// @generated by protoc-gen-connect-es v1.0.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/bazel/buildeventstream/build_event_stream.proto (package build_event_stream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

