// @generated by protoc-gen-es v1.8.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/plugin/grpc_stdio.proto (package plugin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message plugin.StdioData
 */
export declare class StdioData extends Message<StdioData> {
  /**
   * @generated from field: plugin.StdioData.Channel channel = 1;
   */
  channel: StdioData_Channel;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  constructor(data?: PartialMessage<StdioData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "plugin.StdioData";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StdioData;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StdioData;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StdioData;

  static equals(a: StdioData | PlainMessage<StdioData> | undefined, b: StdioData | PlainMessage<StdioData> | undefined): boolean;
}

/**
 * @generated from enum plugin.StdioData.Channel
 */
export declare enum StdioData_Channel {
  /**
   * @generated from enum value: INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: STDOUT = 1;
   */
  STDOUT = 1,

  /**
   * @generated from enum value: STDERR = 2;
   */
  STDERR = 2,
}

